#!/usr/bin/env bash
# Extract the real heredoc from setup.sh and verify each variant is valid JS.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
NEXTDEPLOY_VERSION=0.1.0
APP_NAME=myapp
APP_DIR=/home/ubuntu/myapp
APP_PORT=3000

emit() { # script_bin script_args outfile
  local script_bin="$1" script_args="$2" eco="$3"
  cat > "$eco" <<ECOCONF
// Generated by nextdeploy v$NEXTDEPLOY_VERSION
module.exports = {
  apps: [{
    name: '$APP_NAME',
    cwd: '$APP_DIR',
    script: '$script_bin',
    args: [$script_args],
    interpreter: 'none',
    env: {
      NODE_ENV: 'production',
      PORT: '$APP_PORT',
    },
    autorestart: true,
    max_restarts: 10,
    restart_delay: 2000,
    max_memory_restart: '512M',
  }],
};
ECOCONF
}

FAIL=0
emit npm "'run', 'start'"   /tmp/eco_npm.js
emit yarn "'start'"         /tmp/eco_yarn.js
emit npx  "'next', 'start'" /tmp/eco_npx.js

for f in npm yarn npx; do
  if out=$(node -e "
    const c=require('/tmp/eco_$f.js');
    const a=c.apps[0];
    if(a.name!=='myapp') throw new Error('bad name');
    if(a.cwd!=='/home/ubuntu/myapp') throw new Error('bad cwd');
    if(a.env.PORT!=='3000') throw new Error('bad PORT');
    if(a.env.NODE_ENV!=='production') throw new Error('bad NODE_ENV');
    if(!Array.isArray(a.args)) throw new Error('args not array');
    console.log('  ok  ' + a.script + ' ' + a.args.join(' ') + '  PORT=' + a.env.PORT);
  " 2>&1); then
    echo "$out"
  else
    echo "  FAIL $f: $out"; FAIL=$((FAIL+1))
  fi
done

echo
[ "$FAIL" -eq 0 ] && echo "all ecosystem variants valid" || echo "FAILURES: $FAIL"
[ "$FAIL" -eq 0 ]
