#!/usr/bin/env bash
# Tests for the generated PM2 ecosystem config.
#
# The bug this guards against: the file was written as ecosystem.config.js,
# but a Next.js package.json with "type": "module" makes Node parse every
# .js file as an ES module. `module.exports` then throws
#     ReferenceError: module is not defined in ES module scope
# and PM2 reports only "malformated", which hides the real cause.
# Writing .cjs is CommonJS regardless of what "type" says.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

. lib/ui.sh

NEXTDEPLOY_VERSION=0.1.0
APP_NAME=myapp
APP_PORT=3000

PASS=0; FAIL=0
ok_()   { PASS=$((PASS+1)); printf '  ok    %s\n' "$1"; }
fail_() { FAIL=$((FAIL+1)); printf '  FAIL  %s\n' "$1"; }

WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

# Emit using the same heredoc body as setup.sh. Kept in sync by the
# structural assertions at the bottom, which read setup.sh directly.
emit() { # <dir> <script_bin> <script_args>
  local APP_DIR="$1" script_bin="$2" script_args="$3"
  cat > "$APP_DIR/ecosystem.config.cjs" <<ECOCONF
// Generated by nextdeploy v$NEXTDEPLOY_VERSION
module.exports = {
  apps: [{
    name: '$APP_NAME',
    cwd: '$APP_DIR',
    script: '$script_bin',
    args: [$script_args],
    interpreter: 'none',
    env: {
      NODE_ENV: 'production',
      PORT: '$APP_PORT',
    },
    autorestart: true,
    max_restarts: 10,
    restart_delay: 2000,
    max_memory_restart: '512M',
  }],
};
ECOCONF
}

echo "== config loads for every package manager =="
i=0
for spec in "npm:'run', 'start'" "yarn:'start'" "pnpm:'start'" "bun:'run', 'start'" "npx:'next', 'start'"; do
  bin="${spec%%:*}"; args="${spec#*:}"
  d="$WORK/p$i"; i=$((i+1)); mkdir -p "$d"
  echo '{"name":"x"}' > "$d/package.json"
  emit "$d" "$bin" "$args"
  if out=$(node -e "
    const c=require('$d/ecosystem.config.cjs'); const a=c.apps[0];
    if(a.env.PORT!=='3000') throw new Error('bad PORT');
    if(a.env.NODE_ENV!=='production') throw new Error('bad NODE_ENV');
    if(!Array.isArray(a.args)) throw new Error('args not an array');
    console.log(a.script+' '+a.args.join(' '));
  " 2>&1); then ok_ "$bin -> $out"; else fail_ "$bin: $out"; fi
done

echo
echo "== the ESM case that broke on a real deploy =="

# A Next.js app with "type": "module" — exactly the failing project.
esm="$WORK/esm"; mkdir -p "$esm"
echo '{"name":"loop-practice","type":"module","scripts":{"start":"next start"}}' > "$esm/package.json"
emit "$esm" "npm" "'run', 'start'"

if node -e "require('$esm/ecosystem.config.cjs')" 2>/dev/null; then
  ok_ ".cjs loads under \"type\": \"module\""
else
  fail_ ".cjs still fails under \"type\": \"module\""
fi

# Show the failure is real: the same content as .js must break on a Node
# that honours "type": "module" for .js files. Newer Node auto-detects
# CommonJS syntax, so only assert when this Node actually reproduces it.
cp "$esm/ecosystem.config.cjs" "$esm/ecosystem.config.js"
if node -e "require('$esm/ecosystem.config.js')" 2>/dev/null; then
  ok_ "(this Node auto-detects CJS in .js — .cjs still required for Node 20)"
else
  ok_ ".js genuinely fails here, confirming .cjs is what fixes it"
fi

echo
echo "== setup.sh writes .cjs, not .js =="

if grep -q 'eco="\$APP_DIR/ecosystem\.config\.cjs"' setup.sh; then
  ok_ "writes ecosystem.config.cjs"
else
  fail_ "does not write .cjs — ESM projects will fail"
fi

if grep -q 'ecosystem\.config\.cjs" >> "\$APP_DIR/\.gitignore"' setup.sh; then
  ok_ "gitignores the .cjs file"
else
  fail_ "gitignore entry does not match the file written"
fi

if grep -q 'rm -f "\$APP_DIR/ecosystem\.config\.js"' setup.sh; then
  ok_ "cleans up a stale .js config from an older run"
else
  fail_ "leaves a stale .js config that PM2 might pick up"
fi

echo
echo "== the config is validated before PM2 sees it =="

if grep -q "node -e \"require('\$eco')\"" setup.sh; then
  ok_ "validates with node before pm2 start"
else
  fail_ "no pre-validation — PM2's 'malformated' would hide the real error"
fi

echo
echo "== failure reporting when nothing started =="

if grep -q 'grep -v .\^\\\[TAILING\\\]' setup.sh; then
  ok_ "strips PM2's TAILING banner so empty logs read as empty"
else
  fail_ "an empty log dump would look like 'no errors'"
fi
if grep -q 'the process never started' setup.sh; then
  ok_ "says explicitly when the process never started"
else
  fail_ "does not distinguish 'never started' from 'crashed'"
fi
if grep -q 'pm2 jlist' setup.sh; then
  ok_ "reports PM2's own status for the app"
else
  fail_ "does not report PM2 status"
fi

echo
echo "PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
